-- AlterEnum
ALTER TYPE "AccountType" ADD VALUE 'LINE_OF_CREDIT';
ALTER TYPE "AccountType" ADD VALUE 'RRSP';
ALTER TYPE "AccountType" ADD VALUE 'TFSA';
ALTER TYPE "AccountType" ADD VALUE 'FHSA';
ALTER TYPE "AccountType" ADD VALUE 'RESP';
ALTER TYPE "AccountType" ADD VALUE 'RRIF';
ALTER TYPE "AccountType" ADD VALUE 'LIRA';
ALTER TYPE "AccountType" ADD VALUE 'INVESTMENT';
