-- AlterEnum
ALTER TYPE "AccountType" ADD VALUE IF NOT EXISTS 'LINE_OF_CREDIT';
ALTER TYPE "AccountType" ADD VALUE IF NOT EXISTS 'RRSP';
ALTER TYPE "AccountType" ADD VALUE IF NOT EXISTS 'TFSA';
ALTER TYPE "AccountType" ADD VALUE IF NOT EXISTS 'FHSA';
ALTER TYPE "AccountType" ADD VALUE IF NOT EXISTS 'RESP';
ALTER TYPE "AccountType" ADD VALUE IF NOT EXISTS 'RRIF';
ALTER TYPE "AccountType" ADD VALUE IF NOT EXISTS 'LIRA';
ALTER TYPE "AccountType" ADD VALUE IF NOT EXISTS 'INVESTMENT';
